### ISSUE TITLE
Re-visit overloading of distance score

### ISSUE THREAD

**Issue by MacMcIrish** [loopmediagroup/es-alchemy#236]
https://github.com/loopmediagroup/es-alchemy/blob/c05c19aeda746d342fb940fca171693dd03f93c2/src/resources/action-map.js#L240

Currently, this script re-compiles on every execution which is not great (es has a limit for script compiles per window)

Either remove the overloading of this function, or bake the type check into the script?

**Comment by cayleyh** [comment]
@MacMcIrish what is this issue?

**Comment by simlu** [comment]
@cayleyh This is still necessary and will become a problem.

**Comment by MacMcIrish** [comment]
@krackerman 
To clarify,
We use a language called `painless` in elasticsearch.
When we input `scaleInM` into the script linked above, we use the raw value templated into the script, when we should use a value in the [params](https://github.com/loopmediagroup/es-alchemy/blob/c05c19aeda746d342fb940fca171693dd03f93c2/src/resources/action-map.js#L267-L274) object below.
Can you find the correct syntax in Painless that would say:
```painless
double scaleInM = params.scaleInM === null
  ? Collections.max(doc[params.scale_field].getValues())
  : params.scaleInM;
```
We have tests that cover this code branch, they should alert compilation errors in the es instance.

**Comment by krackerman** [comment]
Fixed in:
https://github.com/loopmediagroup/es-alchemy/pull/423
